#!/usr/bin/env ksh
# -*- coding: utf-8 -*-
export CORE_APP_CASK=(
    adoptopenjdk8
    airtable
    alacritty
    amazon-workspaces
    android-sdk
    aws-vault
    bitwarden
    brave-browser
    cyberduck
    discord
    docker
    figma
    google-backup-and-sync
    google-chrome
    gpg-suite
    hammerspoon
    insomnia
    jdownloader
    keybase
    kindle-comic-converter
    kindle-comic-creator
    kitty
    mediainfo
    meld
    miro
    mpv
    notion
    osxfuse
    rar
    scratch
    signal
    slack
    spotify
    steam
    tandem
    telegram
    tor-browser
    virtualbox
    virtualbox-extension-pack
    virtualbox-beta
    virtualbox-extension-pack-beta
    vscodium
    whatsapp
    zettlr
    zoom
)
